# Generated by Django 4.1.1 on 2022-10-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='td',
            name='task_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
